INSERT INTO ciudad (id, nombre) VALUES
('1','CUENCA'),
('2','GUALACEO'),
('3','PAUTE'),
('4','GIRÓN'),
('5','Sta. ISABEL'),
('6','SÍGSIG'),
('7','Sn. FERNANDO'),
('8','NABÓN'),
('9','PUCARÁ'),
('10','OÑA'),
('11','CHORDELEG'),
('12','EL PAN'),
('13','SEVILLA DE ORO'),
('14','GUACHAPALA'),
('15','CAMILO PONCE ENRÍQUEZ');