# Form implementation generated from reading ui file 'menu_principal.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MenuPrincipal(object):
    def setupUi(self, MenuPrincipal):
        MenuPrincipal.setObjectName("MenuPrincipal")
        MenuPrincipal.setEnabled(True)
        MenuPrincipal.resize(1134, 577)
        MenuPrincipal.setMouseTracking(False)
        MenuPrincipal.setToolTip("")
        MenuPrincipal.setStyleSheet("background: rgb(20, 52, 100);")
        MenuPrincipal.setDocumentMode(False)
        MenuPrincipal.setTabShape(QtWidgets.QTabWidget.TabShape.Triangular)
        self.centralwidget = QtWidgets.QWidget(parent=MenuPrincipal)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.paginas_login = QtWidgets.QStackedWidget(parent=self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 106))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(162, 162, 159))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(135, 135, 132))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(54, 54, 53))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(72, 72, 70))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 106))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(54, 54, 53))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 106))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(162, 162, 159))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(135, 135, 132))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(54, 54, 53))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(72, 72, 70))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 106))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(54, 54, 53))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(54, 54, 53))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 106))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(162, 162, 159))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(135, 135, 132))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(54, 54, 53))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(72, 72, 70))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(54, 54, 53))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(54, 54, 53))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 106))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 106))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 108, 106))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.ToolTipText, brush)
        self.paginas_login.setPalette(palette)
        self.paginas_login.setStyleSheet("")
        self.paginas_login.setObjectName("paginas_login")
        self.pg_login = QtWidgets.QWidget()
        self.pg_login.setObjectName("pg_login")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.pg_login)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.frame_3 = QtWidgets.QFrame(parent=self.pg_login)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setLineWidth(0)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.frame_2 = QtWidgets.QFrame(parent=self.frame_3)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_4.setMinimumSize(QtCore.QSize(800, 250))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../../../Downloads/fondo_login.jpg"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.horizontalLayout_15.addWidget(self.frame_2)
        self.frame_4 = QtWidgets.QFrame(parent=self.frame_3)
        self.frame_4.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"QLineEdit{  \n"
"border: 2px solid gray;                            \n"
"border-radius: 15px;\n"
"}\n"
"\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_7.setContentsMargins(9, 0, 9, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.formFrame = QtWidgets.QFrame(parent=self.frame_4)
        self.formFrame.setStyleSheet("\n"
"QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(40, 167, 69);\n"
"border-top-left-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(232, 232, 232);\n"
"border-top-left-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"color:rgb(35, 35, 35);\n"
"}\n"
"")
        self.formFrame.setObjectName("formFrame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.formFrame)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.label_6 = QtWidgets.QLabel(parent=self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.txt_user = QtWidgets.QLineEdit(parent=self.formFrame)
        self.txt_user.setMinimumSize(QtCore.QSize(0, 40))
        self.txt_user.setStyleSheet("border: 2px solid gray;\n"
"border-radius: 10px;")
        self.txt_user.setObjectName("txt_user")
        self.verticalLayout_6.addWidget(self.txt_user)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout_6.addItem(spacerItem1)
        self.label_3 = QtWidgets.QLabel(parent=self.formFrame)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.txt_contrasenia = QtWidgets.QLineEdit(parent=self.formFrame)
        self.txt_contrasenia.setMinimumSize(QtCore.QSize(0, 40))
        self.txt_contrasenia.setStyleSheet("border: 2px solid gray;\n"
"border-radius: 10px;")
        self.txt_contrasenia.setObjectName("txt_contrasenia")
        self.verticalLayout_6.addWidget(self.txt_contrasenia)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout_6.addItem(spacerItem2)
        self.btn_ingresar = QtWidgets.QPushButton(parent=self.formFrame)
        self.btn_ingresar.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        self.btn_ingresar.setFont(font)
        self.btn_ingresar.setObjectName("btn_ingresar")
        self.verticalLayout_6.addWidget(self.btn_ingresar)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_6.addItem(spacerItem3)
        self.verticalLayout_7.addWidget(self.formFrame)
        self.horizontalLayout_15.addWidget(self.frame_4)
        self.horizontalLayout_15.setStretch(0, 8)
        self.horizontalLayout_15.setStretch(1, 4)
        self.horizontalLayout_13.addWidget(self.frame_3)
        self.horizontalLayout_13.setStretch(0, 5)
        self.paginas_login.addWidget(self.pg_login)
        self.pg_menu_principal = QtWidgets.QWidget()
        self.pg_menu_principal.setObjectName("pg_menu_principal")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.pg_menu_principal)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame = QtWidgets.QFrame(parent=self.pg_menu_principal)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.fr_superior = QtWidgets.QFrame(parent=self.frame)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(48, 63, 62))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 63, 62))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 63, 62))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 63, 62))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 63, 62))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 63, 62))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 63, 62))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 63, 62))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 63, 62))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        self.fr_superior.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Bernard MT Condensed")
        self.fr_superior.setFont(font)
        self.fr_superior.setStyleSheet("QFrame {\n"
"background-color: rgb(48, 63, 62)\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:rgb(255, 255, 255);\n"
"color:rgb(0, 0, 0);\n"
"font: 77 10pt;\n"
"}\n"
"\n"
"QPushButton {\n"
"background-color: rgb(48, 63, 62);\n"
"    color: rgb(108, 108, 106); \n"
"    border: none; \n"
"border-top-left-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"}\n"
"\n"
"\n"
"QLabel\n"
"{\n"
"    font-family: Arial;\n"
"    color: rgb(255, 255, 255);\n"
"    font: bold 50px;\n"
"}\n"
"\n"
"\n"
"")
        self.fr_superior.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.fr_superior.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.fr_superior.setLineWidth(0)
        self.fr_superior.setObjectName("fr_superior")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.fr_superior)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_menu = QtWidgets.QPushButton(parent=self.fr_superior)
        self.btn_menu.setStyleSheet("")
        self.btn_menu.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../TF_BaseDeDatos/images/menu-hamburguesa.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_menu.setIcon(icon)
        self.btn_menu.setIconSize(QtCore.QSize(32, 32))
        self.btn_menu.setObjectName("btn_menu")
        self.horizontalLayout_4.addWidget(self.btn_menu)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.label_22 = QtWidgets.QLabel(parent=self.fr_superior)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_4.addWidget(self.label_22)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        spacerItem6 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.btn_salir = QtWidgets.QPushButton(parent=self.fr_superior)
        self.btn_salir.setMouseTracking(False)
        self.btn_salir.setAutoFillBackground(False)
        self.btn_salir.setStyleSheet("")
        self.btn_salir.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../TF_BaseDeDatos/images/salir-alt.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_salir.setIcon(icon1)
        self.btn_salir.setIconSize(QtCore.QSize(32, 32))
        self.btn_salir.setCheckable(False)
        self.btn_salir.setAutoRepeat(False)
        self.btn_salir.setAutoExclusive(False)
        self.btn_salir.setAutoDefault(False)
        self.btn_salir.setDefault(False)
        self.btn_salir.setObjectName("btn_salir")
        self.horizontalLayout_4.addWidget(self.btn_salir)
        self.verticalLayout_2.addWidget(self.fr_superior)
        self.fr_inferior = QtWidgets.QFrame(parent=self.frame)
        self.fr_inferior.setMinimumSize(QtCore.QSize(0, 500))
        self.fr_inferior.setMaximumSize(QtCore.QSize(16777215, 900))
        self.fr_inferior.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.fr_inferior.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.fr_inferior.setLineWidth(0)
        self.fr_inferior.setObjectName("fr_inferior")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.fr_inferior)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fr_botones_menu = QtWidgets.QFrame(parent=self.fr_inferior)
        self.fr_botones_menu.setMinimumSize(QtCore.QSize(200, 0))
        self.fr_botones_menu.setMaximumSize(QtCore.QSize(0, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.fr_botones_menu.setFont(font)
        self.fr_botones_menu.setAutoFillBackground(False)
        self.fr_botones_menu.setStyleSheet("\n"
"QFrame{\n"
"background-color:rgb(48, 63, 62)\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton{\n"
"background-color:rgb(48, 63, 62);\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(232, 232, 232);\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"color:rgb(35, 35, 35);\n"
"}\n"
"\n"
"QPushButton:hover#quit_button\n"
"{\n"
"   background-color:white;\n"
"}")
        self.fr_botones_menu.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.fr_botones_menu.setLineWidth(0)
        self.fr_botones_menu.setObjectName("fr_botones_menu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.fr_botones_menu)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_usuario = QtWidgets.QPushButton(parent=self.fr_botones_menu)
        self.btn_usuario.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_usuario.setFont(font)
        self.btn_usuario.setMouseTracking(False)
        self.btn_usuario.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.btn_usuario.setAutoFillBackground(False)
        self.btn_usuario.setAutoDefault(False)
        self.btn_usuario.setObjectName("btn_usuario")
        self.verticalLayout_3.addWidget(self.btn_usuario)
        self.btn_Inmueble = QtWidgets.QPushButton(parent=self.fr_botones_menu)
        self.btn_Inmueble.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_Inmueble.setFont(font)
        self.btn_Inmueble.setObjectName("btn_Inmueble")
        self.verticalLayout_3.addWidget(self.btn_Inmueble)
        self.btn_transaccion = QtWidgets.QPushButton(parent=self.fr_botones_menu)
        self.btn_transaccion.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_transaccion.setFont(font)
        self.btn_transaccion.setObjectName("btn_transaccion")
        self.verticalLayout_3.addWidget(self.btn_transaccion)
        self.btn_pendientes = QtWidgets.QPushButton(parent=self.fr_botones_menu)
        self.btn_pendientes.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_pendientes.setFont(font)
        self.btn_pendientes.setObjectName("btn_pendientes")
        self.verticalLayout_3.addWidget(self.btn_pendientes)
        self.btn_historial = QtWidgets.QPushButton(parent=self.fr_botones_menu)
        self.btn_historial.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(16)
        self.btn_historial.setFont(font)
        self.btn_historial.setObjectName("btn_historial")
        self.verticalLayout_3.addWidget(self.btn_historial)
        self.btn_compra = QtWidgets.QPushButton(parent=self.fr_botones_menu)
        self.btn_compra.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(16)
        self.btn_compra.setFont(font)
        self.btn_compra.setObjectName("btn_compra")
        self.verticalLayout_3.addWidget(self.btn_compra)
        self.btn_reportes = QtWidgets.QPushButton(parent=self.fr_botones_menu)
        self.btn_reportes.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(16)
        self.btn_reportes.setFont(font)
        self.btn_reportes.setObjectName("btn_reportes")
        self.verticalLayout_3.addWidget(self.btn_reportes)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem7)
        self.horizontalLayout.addWidget(self.fr_botones_menu)
        self.fr_paginas = QtWidgets.QFrame(parent=self.fr_inferior)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.fr_paginas.setFont(font)
        self.fr_paginas.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.fr_paginas.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.fr_paginas.setLineWidth(1)
        self.fr_paginas.setObjectName("fr_paginas")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.fr_paginas)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.paginas__principales = QtWidgets.QStackedWidget(parent=self.fr_paginas)
        self.paginas__principales.setStyleSheet("background-color: rgb(232, 232, 232);\n"
"\n"
"QLabel\n"
"{\n"
"    color: rgb(60, 60, 60);\n"
"    font: bold 24px;\n"
"}\n"
"\n"
"\n"
"QPushButton{\n"
"font: bold 24px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(40, 167, 69);\n"
"border-top-left-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(170, 170, 170);\n"
"border-top-left-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"color:rgb(35, 35, 35);\n"
"}")
        self.paginas__principales.setObjectName("paginas__principales")
        self.pg_Pendientes = QtWidgets.QWidget()
        self.pg_Pendientes.setStyleSheet("QLabel{\n"
"font: bold 25px;\n"
"\n"
"}\n"
"\n"
"")
        self.pg_Pendientes.setObjectName("pg_Pendientes")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.pg_Pendientes)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.line_2 = QtWidgets.QFrame(parent=self.pg_Pendientes)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_10.addWidget(self.line_2, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(parent=self.pg_Pendientes)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_10.addWidget(self.line, 1, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.pushButton_11 = QtWidgets.QPushButton(parent=self.pg_Pendientes)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet("background-color: rgb(0, 163, 0);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_11.addWidget(self.pushButton_11)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem8)
        self.gridLayout_10.addLayout(self.horizontalLayout_11, 3, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tableWidget_2 = QtWidgets.QTableWidget(parent=self.pg_Pendientes)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.horizontalLayout_3.addWidget(self.tableWidget_2)
        self.groupBox = QtWidgets.QGroupBox(parent=self.pg_Pendientes)
        self.groupBox.setEnabled(True)
        self.groupBox.setStyleSheet("\n"
"\n"
"QLabel\n"
"{\n"
"    color: rgb(60, 60, 60);\n"
"    font: bold 20px;\n"
"}\n"
"\n"
"\n"
"QPushButton{\n"
"height: 50;\n"
"font: bold 24px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(40, 167, 69);\n"
"border-top-left-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(170, 170, 170);\n"
"border-top-left-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"color:rgb(35, 35, 35);\n"
"}")
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(True)
        self.groupBox.setChecked(False)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_31 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_16.addWidget(self.label_31)
        self.lineEdit_11 = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.verticalLayout_16.addWidget(self.lineEdit_11)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_16.addItem(spacerItem9)
        self.label_32 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_16.addWidget(self.label_32)
        self.calendarWidget = QtWidgets.QCalendarWidget(parent=self.groupBox)
        self.calendarWidget.setGridVisible(True)
        self.calendarWidget.setObjectName("calendarWidget")
        self.verticalLayout_16.addWidget(self.calendarWidget)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_16.addItem(spacerItem10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem11)
        self.pushButton_10 = QtWidgets.QPushButton(parent=self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_9.addWidget(self.pushButton_10)
        self.verticalLayout_16.addLayout(self.horizontalLayout_9)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_16.addItem(spacerItem12)
        self.horizontalLayout_10.addLayout(self.verticalLayout_16)
        self.horizontalLayout_3.addWidget(self.groupBox)
        self.gridLayout_10.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.paginas__principales.addWidget(self.pg_Pendientes)
        self.pg_HIstorial = QtWidgets.QWidget()
        self.pg_HIstorial.setObjectName("pg_HIstorial")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.pg_HIstorial)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.tableWidget_3 = QtWidgets.QTableWidget(parent=self.pg_HIstorial)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(0)
        self.tableWidget_3.setRowCount(0)
        self.horizontalLayout_14.addWidget(self.tableWidget_3)
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.pg_HIstorial)
        self.groupBox_2.setEnabled(True)
        self.groupBox_2.setStyleSheet("\n"
"\n"
"QLabel\n"
"{\n"
"    color: rgb(60, 60, 60);\n"
"    font: bold 20px;\n"
"}\n"
"\n"
"\n"
"QPushButton{\n"
"height: 50;\n"
"font: bold 24px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(40, 167, 69);\n"
"border-top-left-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(170, 170, 170);\n"
"border-top-left-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"color:rgb(35, 35, 35);\n"
"}")
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(True)
        self.groupBox_2.setChecked(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_35 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_17.addWidget(self.label_35)
        self.lineEdit_15 = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.verticalLayout_17.addWidget(self.lineEdit_15)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_17.addItem(spacerItem13)
        self.label_36 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_17.addWidget(self.label_36)
        self.calendarWidget_2 = QtWidgets.QCalendarWidget(parent=self.groupBox_2)
        self.calendarWidget_2.setGridVisible(True)
        self.calendarWidget_2.setObjectName("calendarWidget_2")
        self.verticalLayout_17.addWidget(self.calendarWidget_2)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_17.addItem(spacerItem14)
        self.label_37 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_17.addWidget(self.label_37)
        self.lineEdit_16 = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.verticalLayout_17.addWidget(self.lineEdit_16)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_17.addItem(spacerItem15)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem16)
        self.pushButton_12 = QtWidgets.QPushButton(parent=self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_18.addWidget(self.pushButton_12)
        self.verticalLayout_17.addLayout(self.horizontalLayout_18)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_17.addItem(spacerItem17)
        self.horizontalLayout_17.addLayout(self.verticalLayout_17)
        self.horizontalLayout_14.addWidget(self.groupBox_2)
        self.verticalLayout_18.addLayout(self.horizontalLayout_14)
        self.paginas__principales.addWidget(self.pg_HIstorial)
        self.pg_Reportes = QtWidgets.QWidget()
        self.pg_Reportes.setObjectName("pg_Reportes")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.pg_Reportes)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.tabs_reportes = QtWidgets.QTabWidget(parent=self.pg_Reportes)
        self.tabs_reportes.setObjectName("tabs_reportes")
        self.tab_desempenio = QtWidgets.QWidget()
        self.tab_desempenio.setStyleSheet("\n"
"QLabel\n"
"{\n"
"    color: rgb(60, 60, 60);\n"
"    font: bold 24px;\n"
"}\n"
"\n"
"\n"
"QPushButton{\n"
"font: bold 24px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(40, 167, 69);\n"
"border-top-left-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(170, 170, 170);\n"
"border-top-left-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"color:rgb(35, 35, 35);\n"
"}")
        self.tab_desempenio.setObjectName("tab_desempenio")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_desempenio)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_38 = QtWidgets.QLabel(parent=self.tab_desempenio)
        self.label_38.setObjectName("label_38")
        self.gridLayout_7.addWidget(self.label_38, 0, 0, 1, 1)
        self.label_39 = QtWidgets.QLabel(parent=self.tab_desempenio)
        self.label_39.setObjectName("label_39")
        self.gridLayout_7.addWidget(self.label_39, 0, 1, 1, 1)
        self.calendarWidget_3 = QtWidgets.QCalendarWidget(parent=self.tab_desempenio)
        self.calendarWidget_3.setGridVisible(True)
        self.calendarWidget_3.setObjectName("calendarWidget_3")
        self.gridLayout_7.addWidget(self.calendarWidget_3, 1, 0, 1, 1)
        self.calendarWidget_4 = QtWidgets.QCalendarWidget(parent=self.tab_desempenio)
        self.calendarWidget_4.setGridVisible(True)
        self.calendarWidget_4.setObjectName("calendarWidget_4")
        self.gridLayout_7.addWidget(self.calendarWidget_4, 1, 1, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(parent=self.tab_desempenio)
        self.pushButton_13.setMinimumSize(QtCore.QSize(50, 40))
        self.pushButton_13.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout_7.addWidget(self.pushButton_13, 2, 0, 1, 1)
        self.tableWidget_4 = QtWidgets.QTableWidget(parent=self.tab_desempenio)
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(5)
        self.tableWidget_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(4, item)
        self.gridLayout_7.addWidget(self.tableWidget_4, 3, 0, 1, 2)
        self.lineEdit_17 = QtWidgets.QLineEdit(parent=self.tab_desempenio)
        self.lineEdit_17.setMinimumSize(QtCore.QSize(0, 40))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.gridLayout_7.addWidget(self.lineEdit_17, 2, 1, 1, 1)
        self.tabs_reportes.addTab(self.tab_desempenio, "")
        self.tab_porcentaje = QtWidgets.QWidget()
        self.tab_porcentaje.setStyleSheet("\n"
"QLabel\n"
"{\n"
"    color: rgb(60, 60, 60);\n"
"    font: bold 24px;\n"
"}\n"
"\n"
"\n"
"QPushButton{\n"
"font: bold 24px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(40, 167, 69);\n"
"border-top-left-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(170, 170, 170);\n"
"border-top-left-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"color:rgb(35, 35, 35);\n"
"}")
        self.tab_porcentaje.setObjectName("tab_porcentaje")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_porcentaje)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_41 = QtWidgets.QLabel(parent=self.tab_porcentaje)
        self.label_41.setObjectName("label_41")
        self.gridLayout_8.addWidget(self.label_41, 0, 0, 1, 1)
        self.label_40 = QtWidgets.QLabel(parent=self.tab_porcentaje)
        self.label_40.setObjectName("label_40")
        self.gridLayout_8.addWidget(self.label_40, 0, 1, 1, 1)
        self.calendarWidget_5 = QtWidgets.QCalendarWidget(parent=self.tab_porcentaje)
        self.calendarWidget_5.setGridVisible(True)
        self.calendarWidget_5.setObjectName("calendarWidget_5")
        self.gridLayout_8.addWidget(self.calendarWidget_5, 1, 0, 1, 1)
        self.calendarWidget_6 = QtWidgets.QCalendarWidget(parent=self.tab_porcentaje)
        self.calendarWidget_6.setGridVisible(True)
        self.calendarWidget_6.setObjectName("calendarWidget_6")
        self.gridLayout_8.addWidget(self.calendarWidget_6, 1, 1, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(parent=self.tab_porcentaje)
        self.pushButton_14.setMinimumSize(QtCore.QSize(50, 40))
        self.pushButton_14.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout_8.addWidget(self.pushButton_14, 2, 0, 1, 1)
        self.tableWidget_5 = QtWidgets.QTableWidget(parent=self.tab_porcentaje)
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(2)
        self.tableWidget_5.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(1, item)
        self.gridLayout_8.addWidget(self.tableWidget_5, 3, 0, 1, 2)
        self.tabs_reportes.addTab(self.tab_porcentaje, "")
        self.tab_ventas = QtWidgets.QWidget()
        self.tab_ventas.setStyleSheet("\n"
"QLabel\n"
"{\n"
"    color: rgb(60, 60, 60);\n"
"    font: bold 24px;\n"
"}\n"
"\n"
"\n"
"QPushButton{\n"
"font: bold 22px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(40, 167, 69);\n"
"border-top-left-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(170, 170, 170);\n"
"border-top-left-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"color:rgb(35, 35, 35);\n"
"}")
        self.tab_ventas.setObjectName("tab_ventas")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_ventas)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.tableWidget_6 = QtWidgets.QTableWidget(parent=self.tab_ventas)
        self.tableWidget_6.setObjectName("tableWidget_6")
        self.tableWidget_6.setColumnCount(2)
        self.tableWidget_6.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(1, item)
        self.gridLayout_9.addWidget(self.tableWidget_6, 1, 0, 1, 4)
        self.spinBox = QtWidgets.QSpinBox(parent=self.tab_ventas)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(16)
        self.spinBox.setFont(font)
        self.spinBox.setMinimum(2000)
        self.spinBox.setMaximum(2024)
        self.spinBox.setSingleStep(1)
        self.spinBox.setProperty("value", 2000)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_9.addWidget(self.spinBox, 0, 1, 1, 1)
        self.label_42 = QtWidgets.QLabel(parent=self.tab_ventas)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.gridLayout_9.addWidget(self.label_42, 0, 0, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(parent=self.tab_ventas)
        self.pushButton_15.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButton_15.setBaseSize(QtCore.QSize(0, 0))
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout_9.addWidget(self.pushButton_15, 0, 3, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_9.addItem(spacerItem18, 0, 2, 1, 1)
        self.tabs_reportes.addTab(self.tab_ventas, "")
        self.verticalLayout_19.addWidget(self.tabs_reportes)
        self.paginas__principales.addWidget(self.pg_Reportes)
        self.pg_Compra = QtWidgets.QWidget()
        self.pg_Compra.setStyleSheet("\n"
"QLabel\n"
"{\n"
"    color: rgb(60, 60, 60);\n"
"    font: bold 24px;\n"
"}\n"
"\n"
"\n"
"QPushButton{\n"
"font: bold 24px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(40, 167, 69);\n"
"border-top-left-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(170, 170, 170);\n"
"border-top-left-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"color:rgb(35, 35, 35);\n"
"}")
        self.pg_Compra.setObjectName("pg_Compra")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.pg_Compra)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.pg_Compra)
        self.groupBox_3.setCheckable(True)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_34 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_34.setObjectName("label_34")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_34)
        self.lineEdit_24 = QtWidgets.QLineEdit(parent=self.groupBox_3)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_24)
        self.label_44 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_44.setObjectName("label_44")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_44)
        self.lineEdit_23 = QtWidgets.QLineEdit(parent=self.groupBox_3)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_23)
        self.label_45 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_45.setObjectName("label_45")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_45)
        self.lineEdit_22 = QtWidgets.QLineEdit(parent=self.groupBox_3)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_22)
        self.label_46 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_46.setObjectName("label_46")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_46)
        self.comboBox_8 = QtWidgets.QComboBox(parent=self.groupBox_3)
        self.comboBox_8.setObjectName("comboBox_8")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.comboBox_8)
        self.label_49 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_49.setObjectName("label_49")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_49)
        self.lineEdit_20 = QtWidgets.QLineEdit(parent=self.groupBox_3)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_20)
        self.label_51 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_51.setObjectName("label_51")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_51)
        self.lineEdit_18 = QtWidgets.QLineEdit(parent=self.groupBox_3)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_18)
        self.label_52 = QtWidgets.QLabel(parent=self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_52)
        self.horizontalFrame_3 = QtWidgets.QFrame(parent=self.groupBox_3)
        self.horizontalFrame_3.setStyleSheet("QPushButton{\n"
"padding: 12;\n"
"font: bold 20px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(108, 108, 106);\n"
"border-top-left-radius: 0px;\n"
"border-bottom-left-radius: 0px;\n"
"border-bottom-right-radius:0px;\n"
"border-top-right-radius: 0px;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(170, 170, 170);\n"
"border-top-left-radius: 0px;\n"
"border-bottom-left-radius: 0px;\n"
"border-bottom-right-radius: 0px;\n"
"border-top-right-radius: 0px;\n"
"color:rgb(35, 35, 35);\n"
"}\n"
"")
        self.horizontalFrame_3.setObjectName("horizontalFrame_3")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.horizontalFrame_3)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.gridLayout_11.setHorizontalSpacing(5)
        self.gridLayout_11.setVerticalSpacing(6)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.pushButton_16 = QtWidgets.QPushButton(parent=self.horizontalFrame_3)
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout_11.addWidget(self.pushButton_16, 1, 1, 1, 1)
        self.listWidget_3 = QtWidgets.QListWidget(parent=self.horizontalFrame_3)
        self.listWidget_3.setObjectName("listWidget_3")
        self.gridLayout_11.addWidget(self.listWidget_3, 0, 0, 1, 1)
        self.listWidget_4 = QtWidgets.QListWidget(parent=self.horizontalFrame_3)
        self.listWidget_4.setObjectName("listWidget_4")
        self.gridLayout_11.addWidget(self.listWidget_4, 0, 1, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(parent=self.horizontalFrame_3)
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout_11.addWidget(self.pushButton_17, 1, 0, 1, 1)
        self.horizontalLayout_20.addLayout(self.gridLayout_11)
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalFrame_3)
        self.pushButton_19 = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.pushButton_19.setMinimumSize(QtCore.QSize(90, 40))
        self.pushButton_19.setMaximumSize(QtCore.QSize(220, 16777215))
        self.pushButton_19.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.pushButton_19.setObjectName("pushButton_19")
        self.formLayout_4.setWidget(7, QtWidgets.QFormLayout.ItemRole.FieldRole, self.pushButton_19)
        self.verticalLayout_15.addLayout(self.formLayout_4)
        self.gridLayout_12.addWidget(self.groupBox_3, 1, 2, 2, 2)
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.line_9 = QtWidgets.QFrame(parent=self.pg_Compra)
        self.line_9.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_9.setObjectName("line_9")
        self.verticalLayout_23.addWidget(self.line_9)
        self.label_47 = QtWidgets.QLabel(parent=self.pg_Compra)
        self.label_47.setObjectName("label_47")
        self.verticalLayout_23.addWidget(self.label_47)
        self.comboBox_7 = QtWidgets.QComboBox(parent=self.pg_Compra)
        self.comboBox_7.setObjectName("comboBox_7")
        self.verticalLayout_23.addWidget(self.comboBox_7)
        self.label_48 = QtWidgets.QLabel(parent=self.pg_Compra)
        self.label_48.setObjectName("label_48")
        self.verticalLayout_23.addWidget(self.label_48)
        self.comboBox_6 = QtWidgets.QComboBox(parent=self.pg_Compra)
        self.comboBox_6.setObjectName("comboBox_6")
        self.verticalLayout_23.addWidget(self.comboBox_6)
        self.label = QtWidgets.QLabel(parent=self.pg_Compra)
        self.label.setObjectName("label")
        self.verticalLayout_23.addWidget(self.label)
        self.lineEdit_10 = QtWidgets.QLineEdit(parent=self.pg_Compra)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.verticalLayout_23.addWidget(self.lineEdit_10)
        self.label_12 = QtWidgets.QLabel(parent=self.pg_Compra)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_23.addWidget(self.label_12)
        self.comboBox_5 = QtWidgets.QComboBox(parent=self.pg_Compra)
        self.comboBox_5.setObjectName("comboBox_5")
        self.verticalLayout_23.addWidget(self.comboBox_5)
        self.label_30 = QtWidgets.QLabel(parent=self.pg_Compra)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_23.addWidget(self.label_30)
        self.lineEdit_12 = QtWidgets.QLineEdit(parent=self.pg_Compra)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.verticalLayout_23.addWidget(self.lineEdit_12)
        self.label_43 = QtWidgets.QLabel(parent=self.pg_Compra)
        self.label_43.setObjectName("label_43")
        self.verticalLayout_23.addWidget(self.label_43)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setSpacing(20)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.radioButton_3 = QtWidgets.QRadioButton(parent=self.pg_Compra)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout_22.addWidget(self.radioButton_3)
        self.radioButton_2 = QtWidgets.QRadioButton(parent=self.pg_Compra)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_22.addWidget(self.radioButton_2)
        self.radioButton = QtWidgets.QRadioButton(parent=self.pg_Compra)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_22.addWidget(self.radioButton)
        self.radioButton_5 = QtWidgets.QRadioButton(parent=self.pg_Compra)
        self.radioButton_5.setObjectName("radioButton_5")
        self.horizontalLayout_22.addWidget(self.radioButton_5)
        self.radioButton_4 = QtWidgets.QRadioButton(parent=self.pg_Compra)
        self.radioButton_4.setObjectName("radioButton_4")
        self.horizontalLayout_22.addWidget(self.radioButton_4)
        self.verticalLayout_23.addLayout(self.horizontalLayout_22)
        self.gridLayout_12.addLayout(self.verticalLayout_23, 0, 0, 2, 1)
        self.line_7 = QtWidgets.QFrame(parent=self.pg_Compra)
        self.line_7.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout_12.addWidget(self.line_7, 0, 1, 4, 2)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.line_8 = QtWidgets.QFrame(parent=self.pg_Compra)
        self.line_8.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_21.addWidget(self.line_8)
        self.pushButton_18 = QtWidgets.QPushButton(parent=self.pg_Compra)
        self.pushButton_18.setMinimumSize(QtCore.QSize(270, 40))
        self.pushButton_18.setMaximumSize(QtCore.QSize(220, 16777215))
        self.pushButton_18.setObjectName("pushButton_18")
        self.verticalLayout_21.addWidget(self.pushButton_18)
        self.gridLayout_12.addLayout(self.verticalLayout_21, 2, 0, 1, 1)
        self.paginas__principales.addWidget(self.pg_Compra)
        self.pg_Usuarios = QtWidgets.QWidget()
        self.pg_Usuarios.setObjectName("pg_Usuarios")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.pg_Usuarios)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.formGroupBox_3 = QtWidgets.QGroupBox(parent=self.pg_Usuarios)
        self.formGroupBox_3.setStyleSheet("QLabel\n"
"{\n"
"    color: rgb(60, 60, 60);\n"
"    font: bold 24px;\n"
"}\n"
"\n"
"\n"
"QPushButton{\n"
"font: bold 24px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(40, 167, 69);\n"
"border-top-left-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(170, 170, 170);\n"
"border-top-left-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"color:rgb(35, 35, 35);\n"
"}\n"
"\n"
"")
        self.formGroupBox_3.setTitle("")
        self.formGroupBox_3.setObjectName("formGroupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.formGroupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.txt_cedula_usuarios = QtWidgets.QLineEdit(parent=self.formGroupBox_3)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        self.txt_cedula_usuarios.setFont(font)
        self.txt_cedula_usuarios.setObjectName("txt_cedula_usuarios")
        self.gridLayout_3.addWidget(self.txt_cedula_usuarios, 3, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(parent=self.formGroupBox_3)
        self.label_20.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_20.setOpenExternalLinks(False)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 5, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(parent=self.formGroupBox_3)
        self.label_21.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_21.setOpenExternalLinks(False)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 6, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(parent=self.formGroupBox_3)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_3.addWidget(self.comboBox, 6, 1, 1, 1)
        self.tbl_usuarios = QtWidgets.QTableWidget(parent=self.formGroupBox_3)
        self.tbl_usuarios.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tbl_usuarios.setObjectName("tbl_usuarios")
        self.tbl_usuarios.setColumnCount(5)
        self.tbl_usuarios.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_usuarios.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_usuarios.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_usuarios.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_usuarios.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_usuarios.setHorizontalHeaderItem(4, item)
        self.gridLayout_3.addWidget(self.tbl_usuarios, 10, 1, 1, 1)
        self.txt_clave_usuarios = QtWidgets.QLineEdit(parent=self.formGroupBox_3)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        self.txt_clave_usuarios.setFont(font)
        self.txt_clave_usuarios.setObjectName("txt_clave_usuarios")
        self.gridLayout_3.addWidget(self.txt_clave_usuarios, 5, 1, 1, 1)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.pushButton = QtWidgets.QPushButton(parent=self.formGroupBox_3)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_21.addWidget(self.pushButton)
        self.btn_buscar_usuario = QtWidgets.QPushButton(parent=self.formGroupBox_3)
        self.btn_buscar_usuario.setMinimumSize(QtCore.QSize(30, 40))
        self.btn_buscar_usuario.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.btn_buscar_usuario.setObjectName("btn_buscar_usuario")
        self.horizontalLayout_21.addWidget(self.btn_buscar_usuario)
        self.btn_editar_usuarios = QtWidgets.QPushButton(parent=self.formGroupBox_3)
        self.btn_editar_usuarios.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_editar_usuarios.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.btn_editar_usuarios.setObjectName("btn_editar_usuarios")
        self.horizontalLayout_21.addWidget(self.btn_editar_usuarios)
        self.btn_eliminar_usuario = QtWidgets.QPushButton(parent=self.formGroupBox_3)
        self.btn_eliminar_usuario.setMinimumSize(QtCore.QSize(30, 40))
        self.btn_eliminar_usuario.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.btn_eliminar_usuario.setObjectName("btn_eliminar_usuario")
        self.horizontalLayout_21.addWidget(self.btn_eliminar_usuario)
        self.gridLayout_3.addLayout(self.horizontalLayout_21, 8, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(parent=self.formGroupBox_3)
        self.label_16.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_16.setOpenExternalLinks(False)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 2, 0, 1, 1)
        self.txt_apellido_usuarios = QtWidgets.QLineEdit(parent=self.formGroupBox_3)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        self.txt_apellido_usuarios.setFont(font)
        self.txt_apellido_usuarios.setObjectName("txt_apellido_usuarios")
        self.gridLayout_3.addWidget(self.txt_apellido_usuarios, 2, 1, 1, 1)
        self.txt_nombre_usuarios = QtWidgets.QLineEdit(parent=self.formGroupBox_3)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        self.txt_nombre_usuarios.setFont(font)
        self.txt_nombre_usuarios.setObjectName("txt_nombre_usuarios")
        self.gridLayout_3.addWidget(self.txt_nombre_usuarios, 0, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(parent=self.formGroupBox_3)
        self.label_18.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_18.setOpenExternalLinks(False)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 0, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(parent=self.formGroupBox_3)
        self.label_19.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_19.setOpenExternalLinks(False)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 3, 0, 1, 1)
        self.txt_email_usuarios = QtWidgets.QLineEdit(parent=self.formGroupBox_3)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        self.txt_email_usuarios.setFont(font)
        self.txt_email_usuarios.setObjectName("txt_email_usuarios")
        self.gridLayout_3.addWidget(self.txt_email_usuarios, 4, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(parent=self.formGroupBox_3)
        self.label_13.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_13.setOpenExternalLinks(False)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 4, 0, 1, 1)
        self.line_5 = QtWidgets.QFrame(parent=self.formGroupBox_3)
        self.line_5.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_3.addWidget(self.line_5, 7, 1, 1, 1)
        self.line_6 = QtWidgets.QFrame(parent=self.formGroupBox_3)
        self.line_6.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_3.addWidget(self.line_6, 9, 1, 1, 1)
        self.verticalLayout_20.addWidget(self.formGroupBox_3)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_20.addLayout(self.gridLayout_5)
        self.verticalLayout_22.addLayout(self.verticalLayout_20)
        self.paginas__principales.addWidget(self.pg_Usuarios)
        self.pg_Inmueble = QtWidgets.QWidget()
        self.pg_Inmueble.setObjectName("pg_Inmueble")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.pg_Inmueble)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.formGroupBox_2 = QtWidgets.QGroupBox(parent=self.pg_Inmueble)
        self.formGroupBox_2.setStyleSheet("QLabel\n"
"{\n"
"    color: rgb(60, 60, 60);\n"
"    font: bold 24px;\n"
"}\n"
"\n"
"\n"
"QPushButton{\n"
"font: bold 24px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(40, 167, 69);\n"
"border-top-left-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(170, 170, 170);\n"
"border-top-left-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"color:rgb(35, 35, 35);\n"
"}\n"
"\n"
"")
        self.formGroupBox_2.setObjectName("formGroupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.formGroupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalFrame = QtWidgets.QFrame(parent=self.formGroupBox_2)
        self.horizontalFrame.setStyleSheet("QPushButton{\n"
"padding: 12;\n"
"font: bold 20px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(108, 108, 106);\n"
"border-top-left-radius: 0px;\n"
"border-bottom-left-radius: 0px;\n"
"border-bottom-right-radius:0px;\n"
"border-top-right-radius: 0px;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(170, 170, 170);\n"
"border-top-left-radius: 0px;\n"
"border-bottom-left-radius: 0px;\n"
"border-bottom-right-radius: 0px;\n"
"border-top-right-radius: 0px;\n"
"color:rgb(35, 35, 35);\n"
"}\n"
"")
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.gridLayout_6.setHorizontalSpacing(5)
        self.gridLayout_6.setVerticalSpacing(6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.horizontalFrame)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_6.addWidget(self.pushButton_4, 1, 1, 1, 1)
        self.listWidget = QtWidgets.QListWidget(parent=self.horizontalFrame)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_6.addWidget(self.listWidget, 0, 0, 1, 1)
        self.listWidget_2 = QtWidgets.QListWidget(parent=self.horizontalFrame)
        self.listWidget_2.setObjectName("listWidget_2")
        self.gridLayout_6.addWidget(self.listWidget_2, 0, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.horizontalFrame)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_6.addWidget(self.pushButton_3, 1, 0, 1, 1)
        self.horizontalLayout_7.addLayout(self.gridLayout_6)
        self.gridLayout_2.addWidget(self.horizontalFrame, 11, 2, 1, 1)
        self.comboBox_10 = QtWidgets.QComboBox(parent=self.formGroupBox_2)
        self.comboBox_10.setObjectName("comboBox_10")
        self.gridLayout_2.addWidget(self.comboBox_10, 9, 2, 1, 1)
        self.label_24 = QtWidgets.QLabel(parent=self.formGroupBox_2)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 8, 1, 1, 1)
        self.comboBox_9 = QtWidgets.QComboBox(parent=self.formGroupBox_2)
        self.comboBox_9.setObjectName("comboBox_9")
        self.gridLayout_2.addWidget(self.comboBox_9, 8, 2, 1, 1)
        self.label_25 = QtWidgets.QLabel(parent=self.formGroupBox_2)
        self.label_25.setObjectName("label_25")
        self.gridLayout_2.addWidget(self.label_25, 9, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(parent=self.formGroupBox_2)
        self.label_27.setObjectName("label_27")
        self.gridLayout_2.addWidget(self.label_27, 10, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(parent=self.formGroupBox_2)
        self.label_15.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 1, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(parent=self.formGroupBox_2)
        self.label_17.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 5, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.formGroupBox_2)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 6, 2, 1, 1)
        self.label_23 = QtWidgets.QLabel(parent=self.formGroupBox_2)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 7, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(parent=self.formGroupBox_2)
        self.label_14.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 3, 1, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.formGroupBox_2)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_2.addWidget(self.lineEdit_3, 7, 2, 1, 1)
        self.txt_nombre_lab_laboratorios = QtWidgets.QLineEdit(parent=self.formGroupBox_2)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        self.txt_nombre_lab_laboratorios.setFont(font)
        self.txt_nombre_lab_laboratorios.setObjectName("txt_nombre_lab_laboratorios")
        self.gridLayout_2.addWidget(self.txt_nombre_lab_laboratorios, 1, 2, 1, 1)
        self.txt_aforo_laboratorios = QtWidgets.QLineEdit(parent=self.formGroupBox_2)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        self.txt_aforo_laboratorios.setFont(font)
        self.txt_aforo_laboratorios.setObjectName("txt_aforo_laboratorios")
        self.gridLayout_2.addWidget(self.txt_aforo_laboratorios, 3, 2, 1, 1)
        self.txt_software_laboratorio = QtWidgets.QLineEdit(parent=self.formGroupBox_2)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        self.txt_software_laboratorio.setFont(font)
        self.txt_software_laboratorio.setObjectName("txt_software_laboratorio")
        self.gridLayout_2.addWidget(self.txt_software_laboratorio, 5, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.formGroupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 6, 1, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(parent=self.formGroupBox_2)
        self.lineEdit_7.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_2.addWidget(self.lineEdit_7, 10, 2, 1, 1)
        self.label_28 = QtWidgets.QLabel(parent=self.formGroupBox_2)
        self.label_28.setObjectName("label_28")
        self.gridLayout_2.addWidget(self.label_28, 11, 1, 1, 1)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.formGroupBox_2)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_19.addWidget(self.pushButton_2)
        self.btn_editar_lab = QtWidgets.QPushButton(parent=self.formGroupBox_2)
        self.btn_editar_lab.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_editar_lab.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.btn_editar_lab.setObjectName("btn_editar_lab")
        self.horizontalLayout_19.addWidget(self.btn_editar_lab)
        self.btn_buscar_lab = QtWidgets.QPushButton(parent=self.formGroupBox_2)
        self.btn_buscar_lab.setMinimumSize(QtCore.QSize(30, 40))
        self.btn_buscar_lab.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.btn_buscar_lab.setObjectName("btn_buscar_lab")
        self.horizontalLayout_19.addWidget(self.btn_buscar_lab)
        self.btn_eliminar_lab = QtWidgets.QPushButton(parent=self.formGroupBox_2)
        self.btn_eliminar_lab.setMinimumSize(QtCore.QSize(30, 40))
        self.btn_eliminar_lab.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.btn_eliminar_lab.setObjectName("btn_eliminar_lab")
        self.horizontalLayout_19.addWidget(self.btn_eliminar_lab)
        self.gridLayout_2.addLayout(self.horizontalLayout_19, 13, 2, 1, 1)
        self.horizontalLayout_6.addWidget(self.formGroupBox_2)
        self.line_4 = QtWidgets.QFrame(parent=self.pg_Inmueble)
        self.line_4.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_6.addWidget(self.line_4)
        self.tableWidget = QtWidgets.QTableWidget(parent=self.pg_Inmueble)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.horizontalLayout_6.addWidget(self.tableWidget)
        self.paginas__principales.addWidget(self.pg_Inmueble)
        self.pg_Transaccion = QtWidgets.QWidget()
        self.pg_Transaccion.setStyleSheet("\n"
"QLabel\n"
"{\n"
"    color: rgb(60, 60, 60);\n"
"    font: bold 24px;\n"
"}\n"
"\n"
"\n"
"QPushButton{\n"
"height:50;\n"
"font: bold 24px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(40, 167, 69);\n"
"border-top-left-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(170, 170, 170);\n"
"border-top-left-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"color:rgb(35, 35, 35);\n"
"}\n"
"\n"
"\n"
"")
        self.pg_Transaccion.setObjectName("pg_Transaccion")
        self.gridLayout = QtWidgets.QGridLayout(self.pg_Transaccion)
        self.gridLayout.setObjectName("gridLayout")
        self.label_29 = QtWidgets.QLabel(parent=self.pg_Transaccion)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout.addWidget(self.label_29, 1, 1, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem19, 5, 1, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem20, 2, 2, 1, 1)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_14.addItem(spacerItem21)
        self.label_5 = QtWidgets.QLabel(parent=self.pg_Transaccion)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_14.addWidget(self.label_5)
        self.comboBox_2 = QtWidgets.QComboBox(parent=self.pg_Transaccion)
        self.comboBox_2.setObjectName("comboBox_2")
        self.verticalLayout_14.addWidget(self.comboBox_2)
        spacerItem22 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_14.addItem(spacerItem22)
        self.label_7 = QtWidgets.QLabel(parent=self.pg_Transaccion)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_14.addWidget(self.label_7)
        self.comboBox_3 = QtWidgets.QComboBox(parent=self.pg_Transaccion)
        self.comboBox_3.setObjectName("comboBox_3")
        self.verticalLayout_14.addWidget(self.comboBox_3)
        spacerItem23 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_14.addItem(spacerItem23)
        self.label_8 = QtWidgets.QLabel(parent=self.pg_Transaccion)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_14.addWidget(self.label_8)
        self.comboBox_4 = QtWidgets.QComboBox(parent=self.pg_Transaccion)
        self.comboBox_4.setObjectName("comboBox_4")
        self.verticalLayout_14.addWidget(self.comboBox_4)
        spacerItem24 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_14.addItem(spacerItem24)
        self.label_9 = QtWidgets.QLabel(parent=self.pg_Transaccion)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_14.addWidget(self.label_9)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.pg_Transaccion)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_14.addWidget(self.lineEdit)
        spacerItem25 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_14.addItem(spacerItem25)
        self.label_10 = QtWidgets.QLabel(parent=self.pg_Transaccion)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_14.addWidget(self.label_10)
        self.lineEdit_8 = QtWidgets.QLineEdit(parent=self.pg_Transaccion)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.verticalLayout_14.addWidget(self.lineEdit_8)
        spacerItem26 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_14.addItem(spacerItem26)
        self.label_11 = QtWidgets.QLabel(parent=self.pg_Transaccion)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_14.addWidget(self.label_11)
        self.lineEdit_9 = QtWidgets.QLineEdit(parent=self.pg_Transaccion)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.verticalLayout_14.addWidget(self.lineEdit_9)
        spacerItem27 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_14.addItem(spacerItem27)
        self.verticalLayout_13.addLayout(self.verticalLayout_14)
        self.gridLayout.addLayout(self.verticalLayout_13, 2, 1, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.pg_Transaccion)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_8.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.pg_Transaccion)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_8.addWidget(self.pushButton_8)
        self.gridLayout.addLayout(self.horizontalLayout_8, 4, 1, 1, 1)
        spacerItem28 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem28, 0, 1, 1, 1)
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem29, 2, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(parent=self.pg_Transaccion)
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 3, 1, 1, 1)
        self.paginas__principales.addWidget(self.pg_Transaccion)
        self.verticalLayout_4.addWidget(self.paginas__principales)
        self.horizontalLayout.addWidget(self.fr_paginas)
        self.fr_paginas.raise_()
        self.fr_botones_menu.raise_()
        self.verticalLayout_2.addWidget(self.fr_inferior)
        self.verticalLayout_2.setStretch(1, 8)
        self.fr_inferior.raise_()
        self.fr_superior.raise_()
        self.verticalLayout_11.addWidget(self.frame)
        self.paginas_login.addWidget(self.pg_menu_principal)
        self.verticalLayout_9.addWidget(self.paginas_login)
        MenuPrincipal.setCentralWidget(self.centralwidget)

        self.retranslateUi(MenuPrincipal)
        self.paginas_login.setCurrentIndex(1)
        self.paginas__principales.setCurrentIndex(4)
        self.tabs_reportes.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MenuPrincipal)

    def retranslateUi(self, MenuPrincipal):
        _translate = QtCore.QCoreApplication.translate
        MenuPrincipal.setWindowTitle(_translate("MenuPrincipal", "Sistema de Reservas"))
        self.label_6.setText(_translate("MenuPrincipal", " Usuario:"))
        self.label_3.setText(_translate("MenuPrincipal", " Contraseña:"))
        self.btn_ingresar.setText(_translate("MenuPrincipal", "Ingresar"))
        self.label_22.setText(_translate("MenuPrincipal", "Dream Homes"))
        self.btn_usuario.setText(_translate("MenuPrincipal", "Usuario"))
        self.btn_Inmueble.setText(_translate("MenuPrincipal", "Inmueble"))
        self.btn_transaccion.setText(_translate("MenuPrincipal", "Transacción"))
        self.btn_pendientes.setText(_translate("MenuPrincipal", "Pendientes"))
        self.btn_historial.setText(_translate("MenuPrincipal", "Historial"))
        self.btn_compra.setText(_translate("MenuPrincipal", "Compra"))
        self.btn_reportes.setText(_translate("MenuPrincipal", "Reportes"))
        self.pushButton_11.setText(_translate("MenuPrincipal", "Listar"))
        self.groupBox.setTitle(_translate("MenuPrincipal", "Criterio de FIltro"))
        self.label_31.setText(_translate("MenuPrincipal", "Clave Castral:"))
        self.label_32.setText(_translate("MenuPrincipal", "Fecha:"))
        self.pushButton_10.setText(_translate("MenuPrincipal", "  Filltrar  "))
        self.groupBox_2.setTitle(_translate("MenuPrincipal", "Criterio de FIltro"))
        self.label_35.setText(_translate("MenuPrincipal", "Clave Castral:"))
        self.label_36.setText(_translate("MenuPrincipal", "Fecha:"))
        self.label_37.setText(_translate("MenuPrincipal", "Comentario:"))
        self.pushButton_12.setText(_translate("MenuPrincipal", "  Filltrar  "))
        self.label_38.setText(_translate("MenuPrincipal", "Fecha Inicial:"))
        self.label_39.setText(_translate("MenuPrincipal", "Fecha Final:"))
        self.pushButton_13.setText(_translate("MenuPrincipal", "Listar"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("MenuPrincipal", "CEDULA"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("MenuPrincipal", "NOMBRE"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("MenuPrincipal", "APELLIDO"))
        item = self.tableWidget_4.horizontalHeaderItem(3)
        item.setText(_translate("MenuPrincipal", "COMISION"))
        item = self.tableWidget_4.horizontalHeaderItem(4)
        item.setText(_translate("MenuPrincipal", "CALIFICACION"))
        self.tabs_reportes.setTabText(self.tabs_reportes.indexOf(self.tab_desempenio), _translate("MenuPrincipal", "Desempeño Agentes"))
        self.label_41.setText(_translate("MenuPrincipal", "Fecha Inicial:"))
        self.label_40.setText(_translate("MenuPrincipal", "Fecha Final:"))
        self.pushButton_14.setText(_translate("MenuPrincipal", "Listar"))
        item = self.tableWidget_5.horizontalHeaderItem(0)
        item.setText(_translate("MenuPrincipal", "PARROQUIA"))
        item = self.tableWidget_5.horizontalHeaderItem(1)
        item.setText(_translate("MenuPrincipal", "PORCENTAJE"))
        self.tabs_reportes.setTabText(self.tabs_reportes.indexOf(self.tab_porcentaje), _translate("MenuPrincipal", "Porcentaje por Parroquia"))
        item = self.tableWidget_6.horizontalHeaderItem(0)
        item.setText(_translate("MenuPrincipal", "MES"))
        item = self.tableWidget_6.horizontalHeaderItem(1)
        item.setText(_translate("MenuPrincipal", "TOTAL VENTAS"))
        self.label_42.setText(_translate("MenuPrincipal", "Año:"))
        self.pushButton_15.setText(_translate("MenuPrincipal", "Listar"))
        self.tabs_reportes.setTabText(self.tabs_reportes.indexOf(self.tab_ventas), _translate("MenuPrincipal", "Ventas Mensuales"))
        self.groupBox_3.setTitle(_translate("MenuPrincipal", "FIltro"))
        self.label_34.setText(_translate("MenuPrincipal", "Numero de pissos"))
        self.label_44.setText(_translate("MenuPrincipal", "Año construccion"))
        self.label_45.setText(_translate("MenuPrincipal", "Metros de Terrero"))
        self.label_46.setText(_translate("MenuPrincipal", "Ubicacion:"))
        self.label_49.setText(_translate("MenuPrincipal", "Precio Min:"))
        self.label_51.setText(_translate("MenuPrincipal", "Precio Max:"))
        self.label_52.setText(_translate("MenuPrincipal", "Elem/Mate:"))
        self.pushButton_16.setText(_translate("MenuPrincipal", "+ material"))
        self.pushButton_17.setText(_translate("MenuPrincipal", "+ elemento"))
        self.pushButton_19.setText(_translate("MenuPrincipal", "Filltrar"))
        self.label_47.setText(_translate("MenuPrincipal", "Comprador:"))
        self.label_48.setText(_translate("MenuPrincipal", "Inmueble:"))
        self.label.setText(_translate("MenuPrincipal", "Precio de venta:"))
        self.label_12.setText(_translate("MenuPrincipal", "Estado:"))
        self.label_30.setText(_translate("MenuPrincipal", "Comentario:"))
        self.label_43.setText(_translate("MenuPrincipal", "Calificación:"))
        self.radioButton_3.setText(_translate("MenuPrincipal", "Muy Bien"))
        self.radioButton_2.setText(_translate("MenuPrincipal", "Bien"))
        self.radioButton.setText(_translate("MenuPrincipal", "Regular"))
        self.radioButton_5.setText(_translate("MenuPrincipal", "Mal"))
        self.radioButton_4.setText(_translate("MenuPrincipal", "Muy Mal"))
        self.pushButton_18.setText(_translate("MenuPrincipal", "Finalizar Transaccion"))
        self.label_20.setText(_translate("MenuPrincipal", "Correo:"))
        self.label_21.setText(_translate("MenuPrincipal", "Categoria:"))
        item = self.tbl_usuarios.horizontalHeaderItem(0)
        item.setText(_translate("MenuPrincipal", "Nombres"))
        item = self.tbl_usuarios.horizontalHeaderItem(1)
        item.setText(_translate("MenuPrincipal", "Apellidos"))
        item = self.tbl_usuarios.horizontalHeaderItem(2)
        item.setText(_translate("MenuPrincipal", "Cedula"))
        item = self.tbl_usuarios.horizontalHeaderItem(3)
        item.setText(_translate("MenuPrincipal", "Telefono"))
        item = self.tbl_usuarios.horizontalHeaderItem(4)
        item.setText(_translate("MenuPrincipal", "Correo"))
        self.pushButton.setText(_translate("MenuPrincipal", "Crear"))
        self.btn_buscar_usuario.setText(_translate("MenuPrincipal", "Buscar"))
        self.btn_editar_usuarios.setText(_translate("MenuPrincipal", "Editar"))
        self.btn_eliminar_usuario.setText(_translate("MenuPrincipal", "Eliminar"))
        self.label_16.setText(_translate("MenuPrincipal", "Apellidos:"))
        self.label_18.setText(_translate("MenuPrincipal", "Nombres:"))
        self.label_19.setText(_translate("MenuPrincipal", "Cedula:"))
        self.label_13.setText(_translate("MenuPrincipal", "Telefono:"))
        self.pushButton_4.setText(_translate("MenuPrincipal", "+ material"))
        self.pushButton_3.setText(_translate("MenuPrincipal", "+ elemento"))
        self.label_24.setText(_translate("MenuPrincipal", "Ciudad:"))
        self.label_25.setText(_translate("MenuPrincipal", "Parroquia:"))
        self.label_27.setText(_translate("MenuPrincipal", "Año Construccion:"))
        self.label_15.setText(_translate("MenuPrincipal", "Clave Catral:"))
        self.label_17.setText(_translate("MenuPrincipal", "Precio:"))
        self.label_23.setText(_translate("MenuPrincipal", "m2 Terreno:"))
        self.label_14.setText(_translate("MenuPrincipal", "Numero Pisos:"))
        self.label_2.setText(_translate("MenuPrincipal", "m2 Habitables:"))
        self.label_28.setText(_translate("MenuPrincipal", "Elementos:"))
        self.pushButton_2.setText(_translate("MenuPrincipal", "Ingresar"))
        self.btn_editar_lab.setText(_translate("MenuPrincipal", "Editar"))
        self.btn_buscar_lab.setText(_translate("MenuPrincipal", "Buscar"))
        self.btn_eliminar_lab.setText(_translate("MenuPrincipal", "Eliminar"))
        self.label_29.setText(_translate("MenuPrincipal", "Creacion de Transacción"))
        self.label_5.setText(_translate("MenuPrincipal", "Vendedor:"))
        self.label_7.setText(_translate("MenuPrincipal", "Agente:"))
        self.label_8.setText(_translate("MenuPrincipal", "Inmueble"))
        self.label_9.setText(_translate("MenuPrincipal", "Comision:"))
        self.label_10.setText(_translate("MenuPrincipal", "Precio Venta:"))
        self.label_11.setText(_translate("MenuPrincipal", "Comentario:"))
        self.pushButton_7.setText(_translate("MenuPrincipal", "Limpiar"))
        self.pushButton_8.setText(_translate("MenuPrincipal", "Crear"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MenuPrincipal = QtWidgets.QMainWindow()
    ui = Ui_MenuPrincipal()
    ui.setupUi(MenuPrincipal)
    MenuPrincipal.show()
    sys.exit(app.exec())
